### ISSUE TITLE
Hard coded keys

### ISSUE THREAD

**Issue by themakunga** [matmartinez/covid-wallet-pass-chile#2]
In the file api/signature/index.js you have hard coded some signature keys. Even if they are placeholder or test keys they must be null if their are not param value.

**Comment by matmartinez** [comment]
Hey there, @themakunga! The two hardcoded-variables are not keys, but rather **public certificates** (both mine and Apple's). The actual signing keys are retrieved from environment variables. 

I'll close this issue, hit me up if you have any more questions!

Best,
Matías.
